dist: trusty
sudo: required
language: java

addons:
  sonarcloud:
    organization: "xvzhu"
    token:
      secure: 41abd46b86cbe6d3765e3e42941a8d34200f9fd3

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
