dist: trusty
sudo: required
language: java

addons:
  sonarcloud:
    organization: ${SONAR_ORG}
    token: ${SONAR_TOKEN}

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=xvzhu_pooled-connection-client

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
